============================= test session starts ==============================
platform linux -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/runner/work/Assessment-Backend-Week-1/Assessment-Backend-Week-1
collected 112 items

days_api/test_api.py .FFFFFFFFFFFFFFFFFFFF...FFFFFFFFFF.......FFFFFFFFFF [ 45%]
FFFFFFFFFF.FFFFFFFFFFF                                                   [ 65%]
days_api/test_date_functions.py .......................................  [100%]

======================== 61 failed, 51 passed in 0.35s =========================
************* Module app
days_api/app.py:61:0: C0301: Line too long (114/100) (line-too-long)
days_api/app.py:48:4: W0621: Redefining name 'weekday' from outer scope (line 44) (redefined-outer-name)
days_api/app.py:66:8: W0621: Redefining name 'app_history' from outer scope (line 12) (redefined-outer-name)
days_api/app.py:57:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
days_api/app.py:60:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
days_api/app.py:64:15: E0601: Using variable 'app_history' before assignment (used-before-assignment)
days_api/app.py:5:0: W0611: Unused date imported from datetime (unused-import)
days_api/app.py:7:0: W0611: Unused Response imported from flask (unused-import)
days_api/app.py:9:0: W0611: Unused get_current_age imported from date_functions (unused-import)
************* Module date_functions
days_api/date_functions.py:11:8: W0707: Consider explicitly re-raising using 'except ValueError as exc' and 'raise ValueError('Unable to convert value to datetime.') from exc' (raise-missing-from)

-----------------------------------
Your code has been rated at 7.70/10

